import os

# os.system("python3 -m uvicorn app.main:app --reload")
# os.system("python3 -m uvicorn sql_app.main:app --reload")
# os.system("python3 -m uvicorn multiple_file.main:app --reload")
# os.system("python3 -m uvicorn background_tasks.main:app --reload")
# os.system("python3 -m uvicorn test.main:app --reload")
# os.system("python3 -m uvicorn debugging.main:app --reload")
# os.system("python3 -m uvicorn advanced.main:app --reload")
# os.system("python3 -m uvicorn async_sql.main:app --reload")
# os.system("python3 -m uvicorn nosql.main:app --reload")
# os.system("python3 -m uvicorn sub_app.main:app --reload")
# os.system("python3 -m uvicorn behind_proxy.main:app --reload")
# os.system("python3 -m uvicorn template.main:app --reload")
# os.system("python3 -m uvicorn graphql_demo.main:app --reload")
# os.system("python3 -m uvicorn websockets_demo.main:app --reload")
# os.system("python3 -m uvicorn startup_shutdown.main:app --reload")
# os.system("python3 -m uvicorn custom_request.main:app --reload")
# os.system("python3 -m uvicorn test_websocket.main:app --reload")
# os.system("python3 -m uvicorn test_events.main:app --reload")
# os.system("python3 -m uvicorn test_dependency.main:app --reload")
# os.system("ADMIN_EMAIL='deadpool@example.com' APP_NAME='ChimichangApp' python3 -m uvicorn env.main:app --reload")
# os.system("python3 -m uvicorn env.main:app --reload")
# os.system("python3 -m  uvicorn conditional_openapi.main:app --reload")
# os.system("python3 -m  uvicorn openapi_callback.main:app --reload")
# os.system("python3 -m  uvicorn wsgi.main:app --reload")
os.system("python3 -m  uvicorn generate_clients.main:app --reload")
